SunceWallet/sunce

- src/Account/components/AccountTransactions.tsx
- src/Account/components/TransactionList.tsx
- src/Generic/hooks/_caches.ts
- src/Generic/hooks/stellar-subscriptions.ts
- src/Generic/hooks/useFilteredTransactions.ts
- src/Workers/net-worker/stellar-network.ts
Changes here:
- ~decoding tx envelopes in AccountTransactions component. This should be cached (task for later)~ Done on the stellar-network level now and caching decoded txs (see below)
- create `excludeClaimableFilter`: use decoded envelope to check tx operations if all of them are of `createClaimableBalance` type
- created useFilteredTransactions hook, accepting a filter function. For now it is just hardcoded `excludeClaimableFilter`, the plan is to make a UI for this filter later so it could be switched on/off plus adding other filters. TODO: followup with corresponding UI change
- now decoding transaction XDR right away when fetching from horizon and adding to the cache with decoded tx already. So the cache contains transactions decoded (in `decodedTx` attribute). You can take …
> feat: hide Create Claimable Balance transactions

- src/Account/components/AccountTransactions.tsx
- src/Generic/lib/paymentSummary.ts
- src/Generic/lib/transaction.ts
What's done here:
Incoming XLM txs of amount less then 0.001 XLM are considered dust and are hidden from the transaction list (see screenshots below)
Special case: keep showing dust tx if it is coming from our own account (see screenshot below)
Closes #19
Before: 
After:
> feat: filter dust txs

- i18n/locales/en/app-settings.json
- i18n/locales/es/app-settings.json
- i18n/locales/it/app-settings.json
- i18n/locales/ru/app-settings.json
- shared/types/platform.d.ts
- src/Account/components/AccountTransactions.tsx
- src/App/contexts/settings.tsx
- src/AppSettings/components/AppSettings.tsx
- src/AppSettings/components/Settings.tsx
- src/Platform/ipc/web.ts
PR adds two switches in app settings:
- "Show Dust Transactions". Default: off
- "Show Claimable Balance Transactions". Default: off
Manually added EN/RU translations. ES/IT translations made via Deepl.
Closes #20 
**Demo:**
1. Both switched off (default)
2. Switching on "Show Dust" only
3. Switching on both "Show Dust" and "Show Claimable Balance"
4. Switching on "Show Claimable Balance" only
https://github.com/Montelibero/mtl_solar/assets/163447/7816e0a4-0109-4516-92b6-9b39f4f0baae
> feat: add options to toggle Dust and Claimable Balance filters

- src/Generic/hooks/stellar-subscriptions.ts
The reason: sometimes `fetchMoreTransactions` is being called multiple times for the same paging_token. This is likely due to the fact that `fetchMoreTransactions` is being called in `useEffect` and thus may be called multiple times (e.g. on rerender). This is the problem on it is own (excessive requests). However, it was possible that when called twice for the same `paging_token`, the first request updates the cache with new txs and then second requests tries to add the same set of txs to the cache — thus duplicates.
Easy fix is to use local-scoped `prevTransactions` when updating cache — this way the cache will be rewritten, no duplicates. The `inefficiency of multiple requests still stays in the code though, just not visible.`
Proper fix would be to make sure `fetchMoreTransactions` is …
> fix: duplicate txs in transaction history

- src/Account/components/AccountTransactions.tsx
- src/Account/components/SignatureRequestList.tsx
- src/Account/components/TransactionList.tsx
Since #6 hooks like `useLiveRecentTransactions`, `useFilteredTransactions` and `useOlderTransactions` return transactions as `DecodedTransactionResponse` instead of `Horizon.TransactionResponse`. The former type extends the latter with `decodedTx` attribute which you can just use in your components.
```ts
export interface DecodedTransactionResponse extends Horizon.TransactionResponse {
decodedTx: Transaction
}
```
This PR changes `TransactionList` and `SignatureRequestList` components to take advantage of this new attribute instead of decoding XDR in-place with `TransactionBuilder.fromXDR`.
> chore: use already decoded tx from cached DecodedTransactionResponse object

- .github/workflows/mobile.yml
Adds mobile build workflow that outputs as build artifact (doesn't add to release).
The mobile build is manually triggered.
Thanks to @bulbigood for contributions as well.
> Add mobile workflow

- README.md
Release URL pointing to CityChain and the AppImage is not new, it is not used as an installer like most AppImages are.
> Updated Linux section in README 

- src/App/components/AccountList.tsx
Reasons: for a new user this button will already be visible. A user who has more than two accounts will also know about this button.
Its current position at the very beginning of the screen only wastes space. Once configured, users hardly need this button.
> Move “Add account“ card to the end of the account list

- package-lock.json
- package.json
- src/AccountCreation/hooks/useAccountCreation.ts
Proposal for #48  
Solution: Excluded co-signed accounts from public key uniqueness check. 
Performed basic testing on desktop.
> enabled multiple entry of the same account if the account is a co-signer

- src/Account/components/OfferList.tsx
Fix #52 
Looks like that the author's got messed up in the Account class public key fields and used a wrong one.
> Fix #52 Orders from the signer account rather than from co-signed

- src/Generic/lib/transaction.ts
The problem was in incorrect number comparison. Before the fix the check was done wrongly for numbers in e-notation (e.g. 1e-7)
> fix dust tx check

- src/TransactionRequest/components/TransactionRequestContent.tsx
When tx has no replacements (all the fields required for operation are set), the `TransactionStellarUri#replace` fails. We overcome this problem by skipping call to `replace` in this case.
Example of the case leading to error: https://t.me/c/2011632833/1783 (Sunce Wallet Chat in telegram). In this case everything is set (including the source account)
> fix error when signing tx requests with no replacements

- cordova/config/config.template
> I think setting FadeSplashScreen to false should fix the issue, the problem seems related to the splash animation and since the setting will remove the animation it should not cause the issue.
Source: https://github.com/apache/cordova-android/issues/1501#issuecomment-1837298708
> **Added SplashScreenBackgroundColor Preference Support**
> 
> Added support for a general preference to be consistent across platforms for setting the splash screen background color.
> 
> The following order of priority is applied when it comes to the Cordova Android platform:
> 
> AndroidWindowSplashScreenBackground preference
> SplashScreenBackgroundColor preference
> BackgroundColor preference
> #ffffff hardcoded
Source: https://cordova.apache.org/announcements/2024/05/23/cordova-android-13.0.0.html
> make status bar on Android transparent again

- src/Account/components/AccountHeaderCard.tsx
Now you are able to clear the name field completely during the edit. If you will try to save the empty name, the old name will be restored (this was already implemented before). If there is no old name — e.g. you are creating a new account — the wallet won't let you proceed
https://github.com/user-attachments/assets/d043adc1-e73a-4118-ba53-79d3e8484f61
Closes #74
> fix: "Unnamed Account" gets in the way during edit when account name becomes empty

- src/Payment/components/PaymentForm.tsx
On Payment form:
- maximum sendable amount is now always visible (Fixes #80)
- when clicking the max send amount it's value is inserted into the amount field (Fixes #43)
https://github.com/user-attachments/assets/f4db3577-3c12-409a-9ebb-52f8415cbbf1
> feat: add max send button

- src/Payment/components/PaymentForm.tsx
If you send tokens and can't find your counterparty in the saved addresses you can now add it and use it right away
Closes #83
https://github.com/user-attachments/assets/35701fac-c7b1-4438-b565-35542ab51d7e
> feat: allow adding addresses to saved from payment form

- i18n/locales/en/generic.json
- i18n/locales/es/generic.json
- i18n/locales/it/generic.json
- i18n/locales/ru/generic.json
- src/App/css/base-styles.css
- src/Generic/lib/errors.ts
- src/Generic/lib/multisig-service.ts
- src/Payment/components/PaymentDialog.tsx
- src/Payment/components/PaymentForm.tsx
- src/Transaction/components/TransactionSender.tsx
- src/Transaction/lib/stellar-uri.ts
- src/TransactionRequest/components/PaymentRequestContent.tsx
- src/TransactionRequest/components/StellarRequestReviewDialog.tsx
- src/TransactionRequest/components/TransactionRequestContent.tsx
- src/TransactionRequest/components/VerifyTrustedServiceDialog.tsx
- src/Workers/net-worker/multisig.ts
using existing multisig code as much as possible, so when wallet recieves SEP-07 requests with callback it stores a new signatureRequest to activate multisig flow (even if there is just one signature).
When callback is provided the wallet won't publish the tx to the network (according to SEP07 spec).
Different cases handled by different parts of the code (Solar's design):
1. opening web+stellar:tx link by click or QR code scan
2. opening web+stellar:pay link by click or QR code scan
3. opening web+stellar:pay link from Payment Dialog using camera scanner
Closes #87
> feat: support SEP-07 callbacks

- package-lock.json
- package.json
Reason: @stellarguard/stellar-uri blindy casts memo_type parameter in the link to MemoType from stellar-sdk. However, SEP07 memo_type is a string starting with MEMO_ (e.g. MEMO_TEXT), while MemoType is defined as type MemoType = 'none' | 'id' | 'text' | 'hash' | 'return'. Thus the parsed uri contains MEMO_TEXT memoType attribute which Sunce (and @stellar/stellar-sdk) doesn't understand.
Solution is to converge memoType to proper value on the stellar-uri library side. Done here: https://github.com/SunceWallet/stellar-uri/pull/1
Supersedes: #104
> fix: missing memo on SEP07 payment txs

- package-lock.json
- package.json
Reason: `@suncewallet/txrep` was updated to use latest `@stellar/stellar-sdk@13` which is using BigNumber.js@9.1.2. The `@suncewallet/txrep` itself was using `BigNumber.js@4` as direct dependency (probably the same version was used by `stellar-sdk@9`).
`BigNumber.js@9` had breaking changes in API, namely remove `all`, `sub` and `mul` aliases and removed `floor` method. Typescript check failed to find this issues because the check was done against directly imported `BigNumber.js@4`.
Fixed in `@suncewallet/txrep@1.0.2` here: https://github.com/SunceWallet/txrep/commit/7f696635c7c7d0be14a087f5b7a0d47f2db35128
Closes #110
> fix: `n.sequence.add` is not a function

- src/Account/components/AccountBalances.tsx
Before:
After:
Before:
After:
Before:
After:
> fix: make infinity sign for own assets larger. Just for looks

- src/TransactionReview/components/SummaryItem.tsx
MUI uppercases text fields by default. We are using those in readonly mode to show tx operations. However, account data entries are case sensitive, so let's disable uppercasing to preserve original capitalization
https://t.me/c/2011632833/2481
> fix: show operation name without uppercasing

- src/Account/components/AccountBalances.tsx
We were using unicode character which depends on the font. Different platforms have different fonts, on Android it looked quite ugly. Now using svg icon instead of the text.
> fix: make infinity icon look better

- src/Account/components/AccountView.tsx
- src/App/routes.ts
- src/Assets/components/AssetDetailsActions.tsx
- src/Generic/lib/routes.ts
- src/Payment/components/PaymentDialog.tsx
- src/Payment/components/PaymentForm.tsx
Show "Send" button on Asset Details page. Clicking it opens Payment Dialog with asset preselected. Preselected asset can be changed here
Closes #134 
https://github.com/user-attachments/assets/dd99e136-94f7-480a-ae25-50b039df0639
> feat: allow sending from Asset details page

- src/App/contexts/settings.tsx
- src/Generic/lib/threshold.ts
- src/Generic/lib/transaction.ts
Instead of checking against hard coded threshold, we now determining the maximum threshold for tx's operations (e.g. 'med' for 'payment') and use the corresponding account threshold (e.g. 'med_threshold').
The same check is done on signature-coordinator side, however here we want to skip backend completely if multisig is sufficiently signed on creation.
Another part of the fix is done on the multisig backend's side here:
https://github.com/SunceWallet/signature-coordinator/pull/4
In that PR we are setting correct transaction threshold + checking if it was signed enough using the similar calculations like here.
Closes #106 
Related upstream issue: https://github.com/satoshipay/solar/issues/1276
> fix: when checking if multisig tx is fully signed consider ops threshold

- src/Assets/components/AssetDetailsDialog.tsx
- src/Assets/components/BalanceDetailsListItem.tsx
- src/Assets/components/VisibilityIconButton.tsx
Example: USDM (full name is 15 characters)
Solution: moving the fav icon below the balance. Later on there will be another icon buttons here, so it becomes a toolbar for asset actions
Closes #148
> fix: fav icon for asset is not visible on mobile for assets with long names

- src/Account/components/AccountContextMenu.tsx
- Temporarily hidden due to underdeveloped functionality
- Potential Apple moderation complexity concerns
> Hide deposit and withdraw menu items temporarily
